### ISSUE TITLE
Crash with Bitwarden 2023.3.2 CSV

### ISSUE THREAD

**Issue by pjmartorell** [samhwang/bitwarden-to-1password#5]
```ruby
error: Uncaught TypeError: Cannot read properties of undefined (reading 'search')
        if (w.search(/["\n]/) !== -1) {
              ^
    at file:///Users/xxxxxxx/bitwarden-to-1password/lib/utils.ts:28:15
    at Array.map (<anonymous>)
    at arrayToLine (file:///Users/xxxxxxx/bitwarden-to-1password/lib/utils.ts:26:19)
    at file:///Users/xxxxxxx/bitwarden-to-1password/lib/convert.ts:33:74
    at Array.reduce (<anonymous>)
    at write1PasswordCSV (file:///Users/xxxxxxx/bitwarden-to-1password/lib/convert.ts:33:28)
    at convert (file:///Users/xxxxxxx/bitwarden-to-1password/lib/convert.ts:52:5)
    at Command.<anonymous> (file:///Users/xxxxxxx/bitwarden-to-1password/bin/main.ts:21:5)
    at https://deno.land/x/denomander@0.9.3/src/Executor.ts:172:33
    at Array.forEach (<anonymous>)
```

**Comment by samhwang** [comment]
Hey @pjmartorell thanks for submitting the issue.

Do you have a sample input and the command you ran that failed here? Thanks!

**Comment by axlape** [comment]
I have the same issue

**Comment by samhwang** [comment]
hey @axlape, as I said with the original comment, I can't do anything without a sample input that triggered a failure. If you can provide it then I can try to replicate and then come up with a fix.

I don't use BitWarden anymore and migrated to 1P a long while ago (hence the need for the repo), so I can't do another export myself.
